#
# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

openapi: 3.0.3 # must be compatible with quarkus

# Note: the final OpenAPI definition file is produced at build time by merging this data with OpenAPI java annotations.

info:
  title: Nessie API
  version: ${project.version}
  contact:
    name: Project Nessie
    url: https://projectnessie.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths: {} # inferred from java annotations

components:
  examples:

    namespace:
      value: "a.b.c"

    ref:
      value: "main"

    referenceType:
      value: "branch"

    hash:
      value: "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"

    nullHash:
      value:

    refObj:
      value:
        type: BRANCH
        hash: "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"
        name: "main"

    refObjNew:
      value:
        type: BRANCH
        hash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"
        name: "exampleBranch"

    tagObj:
      value:
        type: TAG
        hash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"
        name: "exampleTag"

    ContentKeyGet:
      value: "example.key"

    ContentKey:
      value:
        elements:
          - example
          - key

    namespaceName:
      value: "a.b.c"

    emptyNamespaceName:
      value:

    namespacesResponse:
      value:
        namespaces:
          - type: NAMESPACE
            elements:
              - a
              - b.c
              - d
          - type: NAMESPACE
            elements:
              - a
              - b
              - d

    namespacePropertyUpdate:
      value:
        propertyUpdates:
          - key1: value1
          - key2: value2
        propertyRemovals:
          - key3
          - key4

    iceberg:
      value:
        type: ICEBERG_TABLE
        metadataLocation: "/path/to/metadata/"
        uuid: b874b5d5-f926-4eed-9be7-b2380d9810c0

    expr_by_namespace:
      value: "entry.namespace.startsWith('a.b.c')"
    expr_by_contentType:
      value: "entry.contentType in ['ICEBERG_TABLE','DELTA_LAKE_TABLE']"
    expr_by_namespace_and_contentType:
      value: "entry.namespace.startsWith('some.name.space') && entry.contentType in ['ICEBERG_TABLE','DELTA_LAKE_TABLE']"
    expr_by_commit_author:
      value: "commit.author=='nessie_author'"
    expr_by_commit_committer:
      value: "commit.committer=='nessie_committer'"
    expr_by_commitTime:
      value: "timestamp(commit.commitTime) > timestamp('2021-05-31T08:23:15Z')"
    expr_by_commit_operations_in_namespace:
      value: "operations.exists(op, op.key.startsWith('some.name.space.'))"
    expr_by_commit_operations_table_name:
      value: "operations.exists(op, op.name == 'BaseTable')"
    expr_by_commit_operations_type:
      value: "operations.exists(op, op.type == 'PUT')"
    expr_by_refType:
      value: "refType == 'BRANCH'"
    expr_by_ref_name:
      value: "ref.name == 'my-tag-or-branch'"
    expr_by_ref_commit:
      value: "commit.message == 'invent awesome things'"

    commitMessage:
      value: "Example Commit Message"

    multiGetResponse:
      value:
        contents:
          - content:
              type: ICEBERG_TABLE
              metadataLocation: "/path/to/metadata/"
              uuid: b874b5d5-f926-4eed-9be7-b2380d9810c0
            key:
              elements:
                - example
                - key

    multiGetRequest:
      value:
        requestedKeys:
          - elements:
              - example
              - key

    entriesResponse:
      value:
        token: "xxx"
        entries:
          - name:
              elements:
                - example
                - key
            type: ICEBERG_TABLE

    types:
      value:
        - ICEBERG_TABLE

    merge:
      value:
        fromHash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"

    transplant:
      value:
        hashesToTransplant:
          - "abcdef4242424242424242424242beef00dead42112233445566778899001122"

    operations:
      value:
        commitMeta:
          author: "authorName <authorName@example.com>"
          authorTime: "2021-04-07T14:42:25.534748Z"
          hash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"
          message: "Example Commit Message"
          properties:
            additionalProp1: "xxx"
            additionalProp2: "yyy"
            additionalProp3: "zzz"
          signedOffBy: "signedOffByName <signedOffBy@example.com>"
        operations:
          - type: PUT
            key:
              elements:
                - example
                - key
            content:
              type: ICEBERG_TABLE
              uuid: "b874b5d5-f926-4eed-9be7-b2380d9810c0"
              metadataLocation: "/path/to/metadata/"

    logResponseAdditionalInfo:
      value:
        token: "xxx"
        logEntries:
          - commitMeta:
              author: "authorName <authorName@example.com>"
              authorTime: "2021-04-07T14:42:25.534748Z"
              commitTime: "2021-04-07T14:42:25.534748Z"
              committer: "committerName <committerName@example.com>"
              hash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"
              message: "Example Commit Message"
              properties:
                additionalProp1: "xxx"
                additionalProp2: "yyy"
                additionalProp3: "zzz"
              signedOffBy: "signedOffByName <signedOffBy@example.com>"
            parentCommitHash: "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"
            operations:
              - type: DELETE
                key:
                  elements:
                    - deleted
                    - table
              - type: PUT
                key:
                  elements:
                    - example
                    - key
                content:
                  type: ICEBERG_TABLE
                  uuid: "b874b5d5-f926-4eed-9be7-b2380d9810c0"
                  metadataLocation: "/path/to/metadata/"
    logResponseSimple:
      value:
        token: "xxx"
        logEntries:
          - commitMeta:
              author: "authorName <authorName@example.com>"
              authorTime: "2021-04-07T14:42:25.534748Z"
              commitTime: "2021-04-07T14:42:25.534748Z"
              committer: "committerName <committerName@example.com>"
              hash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"
              message: "Example Commit Message"
              properties:
                additionalProp1: "xxx"
                additionalProp2: "yyy"
                additionalProp3: "zzz"
              signedOffBy: "signedOffByName <signedOffBy@example.com>"

    referencesResponse:
      value:
        token: null
        hasMore: false
        references:
          - type: BRANCH
            hash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"
            name: "exampleBranch"
          - type: TAG
            hash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"
            name: "exampleTag"
          - type: BRANCH
            hash: "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"
            name: "main"

    referencesResponseWithMetadata:
      value:
        token: null
        hasMore: false
        references:
          - type: BRANCH
            hash: "84c57a20c5e956af4af40f3cc34ecc8a9028b9586da135c79011b1867aa3191d"
            name: "main"
            metadata:
              commitMetaOfHEAD:
                hash: "84c57a20c5e956af4af40f3cc34ecc8a9028b9586da135c79011b1867aa3191d"
                committer: ""
                author: "nessie-author"
                signedOffBy: null
                message: "update table"
                commitTime: "2021-11-26T08:01:13.855974Z"
                authorTime: "2021-11-26T08:01:13.852826Z"
                properties: {}
          - type: BRANCH
            hash: "da086850076827d2989c8ee1d7fd22f152f525d46a0441f2b22ad8119c0bbbe5"
            name: "dev"
            metadata:
              numCommitsAhead: 1
              numCommitsBehind: 2
              commonAncestorHash: "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"
              numTotalCommits: 42
              commitMetaOfHEAD:
                hash: "da086850076827d2989c8ee1d7fd22f152f525d46a0441f2b22ad8119c0bbbe5"
                committer: ""
                author: "nessie-author"
                signedOffBy: null
                message: "update table X"
                commitTime: "2021-11-26T08:01:13.834397Z"
                authorTime: "2021-11-26T08:01:13.831371Z"
                properties: {}
          - type: BRANCH
            hash: "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"
            name: "dev2"
            metadata:
              numCommitsAhead: 0
              numCommitsBehind: 2
              commonAncestorHash: "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"
          - type: TAG
            hash: "a682bfdcd5d357b5c964ef07e2eef61fabba42cb8effa8d62357df45a6cc0371"
            name: "testTag1"
            metadata:
              numCommitsAhead: null
              numCommitsBehind: null
              commonAncestorHash: null
              numTotalCommits: 42
              commitMetaOfHEAD:
                hash: "a682bfdcd5d357b5c964ef07e2eef61fabba42cb8effa8d62357df45a6cc0371"
                committer: ""
                author: "nessie-author"
                signedOffBy: null
                message: "update table Y"
                commitTime: "2021-11-23T08:01:14.834397Z"
                authorTime: "2021-11-23T08:01:14.831371Z"
                properties: {}
          - type: TAG
            hash: "da086850076827d2989c8ee1d7fd22f152f525d46a0441f2b22ad8119c0bbbe5"
            name: "testTag2"
            metadata:
              numCommitsAhead: null
              numCommitsBehind: null
              commonAncestorHash: null
              numTotalCommits: 42
              commitMetaOfHEAD:
                hash: "da086850076827d2989c8ee1d7fd22f152f525d46a0441f2b22ad8119c0bbbe5"
                committer: ""
                author: "nessie-author"
                signedOffBy: null
                message: "update table X"
                commitTime: "2021-11-26T08:01:13.834397Z"
                authorTime: "2021-11-26T08:01:13.831371Z"
                properties: {}

    diffResponse:
      value:
        diffs:
          - key:
              elements:
                 - example
                 - key
            from:
              type: ICEBERG_TABLE
              id: "f350b391-f492-41eb-9959-730a8c49f01e"
              metadataLocation: "/path/to/metadata/"
              snapshotId: 23
              schemaId: 15
              specId: 15
              sortOrderId: 15
            to:
              type: ICEBERG_TABLE
              id: "dec31d0a-7d4b-4534-8c24-24f08eda33b2"
              metadataLocation: "/path/to/metadata/"
              snapshotId: 24
              schemaId: 16
              specId: 16
              sortOrderId: 16
